version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/multilingual_faq
  mongo:
    image: "mongo"
  redis:
    image: "redis"
